package com.healthtech.demo.enums;


public enum Especialidad {
PSICOLOGÍA_COGNITIVO_CONDUCTUAL,
PSICOLOGÍA_GESTALT,
PSICOLOGÍA_HUMANISTA,
PSICOLOGÍA_PSICOANALÍTICA,
TERAPIA_FAMILIAR_Y_SISTÉMICA,
MINDFULNESS_Y_TERAPIAS_BASADAS_EN_LA_ATENCIÓN_PLENA,
}
